apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cnpg-operator
  labels:
    environment: cnpg
  # annotations:
  #   argocd.argoproj.io/sync-wave: “1”
spec:
  generators:
  - clusters: {}
      # selector:
      #   matchLabels:
      #     cluster-type: minion
  template:
    metadata:
      name: 'cnpg-operator'
      labels:
        app: 'cnpg'
        client: 'platform'
    spec:
      project: platform-project
      source:
        # https://github.com/cloudnative-pg/charts
        # https://github.com/cloudnative-pg/charts/blob/main/charts/cloudnative-pg/README.md
        repoURL: https://cloudnative-pg.github.io/charts
        chart: cloudnative-pg
        targetRevision: "0.22.0"
        helm:
          version: v3
          # https://github.com/cloudnative-pg/charts/blob/main/charts/cloudnative-pg/values.yaml
          # values: |
          #   # replicas: 3
          #   # resourcesCrossplane:
          #   #   requests:
          #   #     cpu: 250m
          #   #     memory: 512Mi
          #   #   limits:
          #   #     cpu: 250m
          #   #     memory: 512Mi
          #   # resourcesRBACManager:
          #   #   requests:
          #   #     cpu: 250m
          #   #     memory: 512Mi
          #   #   limits:
          #   #     cpu: 250m
          #   #     memory: 512Mi
      destination:
        # server: https://kubernetes.default.svc
        server: {{ .server }}
        namespace: cnpg-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        # https://foxutech.medium.com/how-to-fix-too-long-must-have-at-most-262144-bytes-in-argocd-2a00cddbbe99
        # https://www.arthurkoziel.com/fixing-argocd-crd-too-long-error/
        # https://github.com/CrunchyData/postgres-operator/issues/3633
        # https://argo-cd.readthedocs.io/en/latest/proposals/server-side-apply/
        - ServerSideApply=true

