apiVersion: batch/v1
kind: Job
metadata:
  name: simple-java-app
  labels:
    app: simple-java-app
spec:
  template:
    metadata:
      labels:
        app: simple-java-app
    spec:
      containers:
      - name: simple-java-app
        image: simple-java-app
        command: ["java", "com.example.HelloWorld"]
      restartPolicy: Never
  backoffLimit: 4