apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-gin-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-gin-app
  template:
    metadata:
      labels:
        app: template-gin-app
    spec:
      containers:
        - name: template-gin-app
          image: template-gin-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi