apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  clusterIP: None
  ports:
    - port: 5000
      name: {{ .Chart.Name }}
  selector:
    app: {{ .Chart.Name }}
