repos:
  - repo: local
    hooks:
      - id: python-deps-drift
        name: Python dependency drift (uv export vs committed lock)
        entry: bash third_party/python/drift_check.sh
        language: system
        pass_filenames: false
        stages: [pre-commit]
        files: ^third_party/python/(pyproject.toml|uv.lock|requirements_lock_3_11.txt)$
      - id: ruff-lint
        name: ruff lint (uv)
        entry: bash -c 'cd third_party/python && uv run ruff check --fix --statistics ../..' 
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: ruff-format
        name: ruff format (uv)
        entry: bash -c 'cd third_party/python && uv run ruff format ../..' 
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: pytest
        name: pytest (uv test group)
        entry: bash -c 'cd third_party/python && uv run --group test pytest -q'
        language: system
        pass_filenames: false
        stages: [pre-commit]
  # Check formatting and lint for starlark code
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: 6.3.3
    hooks:
      - id: buildifier
      - id: buildifier-lint
  # Markdown lint
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.14.0
    hooks:
      - id: markdownlint-cli2
        additional_dependencies: []
        files: \.(md|markdown)$
