repos:
  - repo: local
    hooks:
      - id: python-deps-drift
        name: Python dependency drift (uv export vs committed lock)
        entry: bash third_party/python/drift_check.sh
        language: system
        pass_filenames: false
        stages: [commit]
        files: ^third_party/python/(pyproject.toml|uv.lock|requirements_lock_3_11.txt)$
