apiVersion: skaffold/v4beta6
kind: Config

requires:
  # Infrastructure as Code (IaC)
  # - path: ./infrastructure/pulumi_dev_local
  # Python Applications
  - path: ./projects/py/devops_fastapi_app
  - path: ./projects/py/echo_fastapi_app
  - path: ./projects/py/calculator_flask_app
  - path: ./projects/py/helloworld_py_app
  - path: ./projects/py/calculator_cli_py_app
  - path: ./projects/py/awesome_fastapi_app
  # Java Applications
  - path: ./projects/java/hello_springboot_app
  - path: ./projects/java/simple_java_app
  - path: ./projects/java/example1_java_app
  - path: ./projects/java/example2_java_app
  - path: ./projects/java/rs_springboot_app
  # Template Applications
  - path: ./projects/template/template_fastapi_app
  - path: ./projects/template/template_gin_app
  - path: ./projects/template/template_typer_app
  # Complex Polyglot Applications
  # - path: ./projects/microservices-demo
  # Base applications are templates only - no Skaffold configs needed
  # - path: ./projects/base_fastapi_app    # Nothing to skaffold here!
  # - path: ./projects/base_gin_app        # Nothing to skaffold here!
  # - path: ./projects/base_springboot_app # Nothing to skaffold here!

# See:
# - https://skaffold.dev/docs/references/yaml/
# - https://www.youtube.com/watch?v=qS_4Qf8owc0
# - https://github.com/GoogleContainerTools/skaffold/tree/main/examples/multi-config-microservices
# - https://github.com/GoogleContainerTools/skaffold/tree/main/examples/microservices
# - https://codelabs.developers.google.com/skaffold-deep-dive#0
# - https://skaffold.dev/docs/environment/local-cluster/
# - https://skaffold.dev/docs/quickstart/#use-skaffold-for-continuous-development
