apiVersion: v1
kind: Service
metadata:
  name: echo-fastapi-app
  labels:
    app: echo-fastapi-app
spec:
  selector:
    app: echo-fastapi-app
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP