apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-fastapi-app
  labels:
    app: template-fastapi-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: template-fastapi-app
  template:
    metadata:
      labels:
        app: template-fastapi-app
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: template-fastapi-app
        image: template-fastapi-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_SERVER
          value: postgres
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: POSTGRES_DB
          value: app
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: secret-key
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5 