apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: template-fastapi-app-db-credentials
  namespace: template-fastapi-app # Target namespace for the synced secret
spec:
  refreshInterval: "1h" # How often to check the source secret for changes
  secretStoreRef:
    name: external-secret-cluster-fake-cnpg-secrets # Use the new fake CNPG store
    kind: ClusterSecretStore
  target:
    name: template-fastapi-app-db-credentials # Name of the secret to create in this namespace
    creationPolicy: Owner
  data:
  # These keys should match the keys provided by the fake store
  - secretKey: username
    remoteRef:
      key: username # Corresponds to the key in the fake store's data block
      version: "v1"   # Added version field
      # property: username # Property is not needed for fake provider key/value
  - secretKey: password
    remoteRef:
      key: password # Corresponds to the key in the fake store's data block
      version: "v1"   # Added version field
      # property: password # Property is not needed for fake provider key/value 