apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - secrets.yaml
  - configmap.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - istio-telemetry.yaml

namespace: template-fastapi-app

commonLabels:
  app.kubernetes.io/name: template-fastapi-app
  app.kubernetes.io/instance: template-fastapi-app
  app.kubernetes.io/part-of: template-fastapi-app 