apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  # NOTE: Kubernetes Secret data values MUST be valid base64 strings (no brackets or inline comments)
  secret-key: REDACTED_SECRET  # secret-key-for-development-only (base64 encoded)
