apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  username: cG9zdGdyZXM=  # postgres (base64 encoded)
  password: cG9zdGdyZXM=  # postgres (base64 encoded)
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  secret-key: c2VjcmV0LWtleS1mb3ItZGV2ZWxvcG1lbnQtb25seQ==  # secret-key-for-development-only (base64 encoded) 