apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: crossplane
  labels:
    environment: crossplane
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=zero"]
  generators:
  - clusters: {}


  template:
    metadata:
      name: crossplane
      labels:
        app: crossplane
        client: developers
    spec:
      project: platform-project
      source:
        repoURL: https://charts.crossplane.io/stable
        chart: crossplane
        targetRevision: "1.16.0"
        helm:
          version: v3
          values: |
            resourcesCrossplane:
              requests:
                cpu: 250m
                memory: 512Mi
              limits:
                cpu: 250m
                memory: 512Mi
            resourcesRBACManager:
              requests:
                cpu: 250m
                memory: 512Mi
              limits:
                cpu: 250m
                memory: 512Mi
      destination:
        server: '{{.server}}'
        namespace: crossplane-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
