# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: datadog-external-secrets
#   namespace: datadog
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: external-secret-cluster-org-common-secrets
#   target:
#     creationPolicy: Owner
#     name: datadog
#   data:
#   - secretKey: token
#     remoteRef:
#       key: datadog_api_key
#   - secretKey: api-key
#     remoteRef:
#       key: datadog_api_key
#   - secretKey: app-key
#     remoteRef:
#       key: datadog_app_key
# ---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: datadog-external-secrets
  namespace: datadog
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secret-cluster-lab-secrets
  target:
    creationPolicy: Owner
    name: datadog
  data:
  - secretKey: token
    remoteRef:
      key: DATADOG_API_KEY
  - secretKey: api-key
    remoteRef:
      key: DATADOG_API_KEY
  - secretKey: app-key
    remoteRef:
      key: DATADOG_APP_KEY
