version: '2.1'

setup: true

jobs:
  build:
    machine:
      # https://circleci.com/developer/machine/image/ubuntu-2204
      image: default
    # If running ARM, the resource class needs to be added. Omitting this defaults to amd64
    # resource_class: arm.medium
    steps:
      - checkout
      # Whatever you want to do
      # BB: https://bluecentre.buildbuddy.io/settings/org/api-keys
      # CircleCI: https://app.circleci.com/settings/project/github/BlueCentre/monorepo/environment-variables
      - run: sudo /bin/sh -c 'wget https://github.com/bazelbuild/bazelisk/releases/download/v1.18.0/bazelisk-linux-amd64 -O /usr/local/bin/bazel && chmod +x /usr/local/bin/bazel'
      - run: bazel build //... --config=ci --remote_header=x-buildbuddy-api-key=${BUILDBUDDY_ORG_API_KEY}
      - run: bazel test //... --config=ci --remote_header=x-buildbuddy-api-key=${BUILDBUDDY_ORG_API_KEY}
