apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: k8s@clusterissuer.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: kong
          ingressTemplate:
            metadata:
              annotations:
                "external-dns.alpha.kubernetes.io/sync-enabled": "true"
