apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: pulumi

build:
  artifacts:
    - image: gcr.io/k8s-skaffold/skaffold-custom
      custom:
        buildCommand: |
          # Navigate to monorepo root first
          # MONOREPO_ROOT=$(cd ../../.. && pwd)
          # cd $MONOREPO_ROOT

          # Run pulumi commands
          # pulumi up --refresh --yes
          # pulumi preview --refresh --diff
          pulumi preview

          # Build the Docker image
          # docker build -t $IMAGE .

          # Clean up
          # rm -rf $TEMP_DIR
        dependencies:
          paths:
            - "**/*"
  local:
    push: false
    useBuildkit: false

manifests:
  rawYaml:
    - kubernetes/debug/debug-job.yaml

deploy:
  kubectl:
  