apiVersion: v1
kind: Service
metadata:
  name: devops-fastapi-app
  labels:
    app: devops-fastapi-app
spec:
  clusterIP: None
  ports:
    - port: 5000
      name: devops-fastapi-app
  selector:
    app: devops-fastapi-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-fastapi-app
  labels:
    app: devops-fastapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-fastapi-app
  template:
    metadata:
      labels:
        app: devops-fastapi-app
    spec:
      containers:
      - name: devops-fastapi-app
        image: flyr.io/bazel/devops-fastapi-app
        ports:
        - containerPort: 5000
          name: http
