apiVersion: apps/v1
kind: Deployment
metadata:
  name: rs-springboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rs-springboot-app
  template:
    metadata:
      labels:
        app: rs-springboot-app
    spec:
      containers:
        - name: rs-springboot-app
          image: rs-springboot-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            # Adjusted for observed worst-case ~120s cold start (slow JIT/classpath init)
            initialDelaySeconds: 90
            periodSeconds: 5
            timeoutSeconds: 4
            failureThreshold: 12  # 90s + (12*5)=150s window
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            # Start liveness only after likely startup completion
            initialDelaySeconds: 150
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi