apiVersion: v1
kind: Service
metadata:
  name: hello-springboot-app
  labels:
    app: hello-springboot-app
spec:
  clusterIP: None
  ports:
    - port: 8080
      name: hello-springboot-app
  selector:
    app: hello-springboot-app
