apiVersion: batch/v1
kind: Job
metadata:
  name: fastapi-debug-python-path
  namespace: template-fastapi-app
spec:
  template:
    spec:
      containers:
      - name: debug
        image: template-fastapi-app:e9400af-dirty
        command: ["python", "-c", "import sys; print(sys.path)"]
      restartPolicy: Never
  backoffLimit: 0 