# See: https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v4beta5
kind: Config
metadata:
  # skaffold build -m devops-fastapi-app-config
  name: devops-fastapi-app-config

build:
  local:
    push: false
  artifacts:
  - image: flyr.io/bazel/devops-fastapi-app
    custom:
      buildCommand: ./scripts/build.sh
      dependencies:
        paths:
          - ../base_fastapi_app/**
          - app/**
          - bin/**
          - tests/**
          - kubernetes/**
          - kustomize/overlays/dev**
          - helm-charts/**
          - scripts/**
          - ./BUILD.bazel
          - ./skaffold.yaml   # TODO: Likely not needed since skaffold does not apply changes on reload
        ignore:
          - ./**.md
          - tmp/**

manifests:
  # rawYaml:
  #   - kubernetes/*
  kustomize:
    paths:
    # - "./kustomize/base"
    - "./kustomize/overlays/dev"
    # - "./kustomize/overlays/stg"
    # - "./kustomize/overlays/int"
    # - "./kustomize/overlays/prd"
  # helm: # Does not work
  #   releases:
  #   - name: devops-fastapi-app-chart
  #     chartPath: ./helm-charts
  #     overrides:
  #       image: flyr.io/bazel/devops-fastapi-app

# deploy:
#   helm:
#     releases:
#     - name: devops-fastapi-app-chart
#       chartPath: ./helm-charts
#       overrides:
#         image: flyr.io/bazel/devops-fastapi-app

# TODO: Should we use this approach instead of forwarding? (https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/)
portForward:
- resourceType: deployment
  # resourceName: devops-fastapi-app       # rawYaml
  resourceName: dev-devops-fastapi-app   # kustomize
  # resourceName: devops-fastapi-app-chart # helm
  port: 5000
  localPort: 5000



# See:
# - https://github.com/GoogleContainerTools/skaffold/blob/main/examples/multi-config-microservices/skaffold.yaml
# - https://github.com/GoogleContainerTools/skaffold/blob/main/examples/structure-tests/skaffold.yaml

# NOTE: Only works with the old rules_docker approach
# apiVersion: skaffold/v4beta5
# kind: Config
# build:
#   artifacts:
#   - image: skaffold-bazel
#     bazel:
#       target: //:skaffold_example.tar
