apiVersion: skaffold/v4beta5
kind: Config
metadata:
  # skaffold build -m py-devops-fastapi-app-config
  name: py-devops-fastapi-app-config

build:
  local:
    push: false
  artifacts:
  - image: flyr.io/bazel/py-devops-fastapi-app
    custom:
      buildCommand: ./build.sh
      dependencies:
        paths:
          - app/**
          - tests/**
          - kubernetes/**
          - ./BUILD.bazel
          - ./build.sh
        ignore:
          - README*
          - tmp/**

manifests:
  rawYaml:
    - kubernetes/*

portForward:
- resourceType: deployment
  resourceName: py-devops-fastapi-app
  port: http
  localPort: 5000

  # - image: my-app:latest
  #   bazel:
  #     target: //my-app:image
  # - image: my-other-app:latest
  #   bazel:
  #     target: //my-other-app:image
# deploy:
#   kubectl:
#     manifests:
#     - k8s/k8s-pod.yaml
#   kustomize:
#     configs:
#     - k8s/kustomization.yaml
# profiles:
# - name: development
#   helm:
#     chart: my-app
#     version: 0.1.0
#     values:
#       ENVIRONMENT: development
# - name: production
#   helm:
#     chart: my-app
#     version: 0.1.0
#     values:
#       ENVIRONMENT: production
# portForward:
#   - resourceType: deployment
#     resourceName: leeroy-web
#     port: 8080
#     localPort: 9000
#   - resourceType: deployment
#     resourceName: leeroy-app
#     port: http
#     localPort: 9001


# See:
# - https://github.com/GoogleContainerTools/skaffold/blob/main/examples/multi-config-microservices/skaffold.yaml
# - https://github.com/GoogleContainerTools/skaffold/blob/main/examples/structure-tests/skaffold.yaml

# apiVersion: skaffold/v4beta5
# kind: Config
# build:
#   artifacts:
#   - image: skaffold-bazel
#     bazel:
#       target: //:skaffold_example.tar
