apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
  namespace: template-fastapi-app
data:
  config.yaml: |
    domain: template-fastapi-app-domain
    descriptors:
      # Global rate limit for all API endpoints
      - key: generic_key
        value: default
        rate_limit:
          unit: minute
          requests_per_unit: 20
      
      # Rate limit for our specific test endpoint
      - key: generic_key
        value: "/api/v1/rate-limited/rate-limited"
        rate_limit:
          unit: minute
          requests_per_unit: 3
      
      # Path-based rate limits
      - key: path
        value: /api/v1/rate-limited/rate-limited
        rate_limit:
          unit: minute
          requests_per_unit: 3
      
      # Auth-based rate limits with different values
      - key: auth
        value: authenticated
        rate_limit:
          unit: minute
          requests_per_unit: 15
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratelimit
  namespace: template-fastapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratelimit
  template:
    metadata:
      labels:
        app: ratelimit
    spec:
      initContainers:
      - name: wait-for-redis
        image: busybox:latest
        command: ['sh', '-c', 'until nc -z redis 6379; do echo "Waiting for Redis..."; sleep 2; done; echo "Redis is ready!"']
      containers:
      - name: ratelimit
        image: envoyproxy/ratelimit:v1.4.0
        imagePullPolicy: IfNotPresent
        command: ["/bin/ratelimit"]
        env:
        - name: RUNTIME_ROOT
          value: /data
        - name: RUNTIME_SUBDIRECTORY
          value: config
        - name: RUNTIME_WATCH_ROOT
          value: "false"
        - name: RUNTIME_IGNOREDOTFILES
          value: "true"
        - name: PORT
          value: "8080"
        - name: GRPC_PORT
          value: "8081"
        - name: USE_STATSD
          value: "false"
        - name: LOG_LEVEL
          value: "debug"
        - name: REDIS_SOCKET_TYPE
          value: "tcp"
        - name: REDIS_URL
          value: "redis:6379"
        ports:
        - containerPort: 8080
        - containerPort: 8081
        volumeMounts:
        - name: config
          mountPath: /data/config/config.yaml
          subPath: config.yaml
      volumes:
      - name: config
        configMap:
          name: ratelimit-config
---
apiVersion: v1
kind: Service
metadata:
  name: ratelimit
  namespace: template-fastapi-app
spec:
  selector:
    app: ratelimit
  ports:
  - port: 8080
    name: http
  - port: 8081
    name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: template-fastapi-app
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    name: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: template-fastapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379 