apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cnpg-cluster
  labels:
    environment: cnpg
  # annotations:
  #   argocd.argoproj.io/sync-wave: “1”
spec:
  generators:
  - clusters: {}
      # selector:
      #   matchLabels:
      #     cluster-type: minion
  template:
    metadata:
      name: 'cnpg-cluster'
      labels:
        app: cnpg
        client: platform
    spec:
      project: platform-project
      source:
        # https://github.com/cloudnative-pg/charts
        # https://github.com/cloudnative-pg/charts/blob/main/charts/cluster/README.md
        repoURL: https://cloudnative-pg.github.io/charts
        chart: cluster
        targetRevision: "0.0.9"
        helm:
          version: v3
          # https://github.com/cloudnative-pg/charts/blob/main/charts/cluster/values.yaml
          values: |
            mode: standalone
            cluster:
              instances: 1
            backups:
              enabled: false
      destination:
        # server: https://kubernetes.default.svc
        server: {{ .server }}
        namespace: cnpg-cluster
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
