resources:
- ../../base
namePrefix: dev-
# patches:
# - path: patch.yaml
configMapGenerator:
- name: devops-fastapi-app-configmap
  behavior: replace
  files:
    - application.properties
  literals:
    - foo=bar
  env: dev.env
