apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: example2-java-app

build:
  artifacts:
    - image: example2-java-app
      custom:
        buildCommand: |
          # Navigate to monorepo root first
          MONOREPO_ROOT=$(cd ../../.. && pwd)
          cd $MONOREPO_ROOT

          # Run code tests before building artifacts
          bazel test //projects/java/example2_java_app/...

          # Then build the binary
          bazel build //projects/java/example2_java_app/src/main/java/com/example:JavaLoggingClient

          # Create a simple Dockerfile for the Java app
          TEMP_DIR=$(mktemp -d)
          cat > $TEMP_DIR/Dockerfile << 'EOF'
          FROM openjdk:11-jre-slim
          
          # Copy the application
          COPY . /app
          WORKDIR /app
          
          # Create entrypoint script
          RUN echo '#!/bin/bash\njava com.example.JavaLoggingClient' > /app/entrypoint.sh && chmod +x /app/entrypoint.sh
          
          # Command to run the application
          ENTRYPOINT ["/app/entrypoint.sh"]
          EOF

          # Copy application files
          cp -r projects/java/example2_java_app/src $TEMP_DIR/
          
          # Build the Docker image
          docker build -t $IMAGE $TEMP_DIR

          # Clean up
          rm -rf $TEMP_DIR
        dependencies:
          paths:
            - "src/**/*"
            - "schema/**/*"
            - "BUILD.bazel"
  local:
    push: false
    useBuildkit: false

manifests:
  rawYaml:
    - kubernetes/job.yaml

deploy:
  kubectl: {}

profiles:
  - name: dev
    activation:
      - command: dev
    patches:
      - op: add
        path: /build/local/push
        value: false
      - op: add
        path: /deploy/kubectl/flags
        value:
          apply:
            - --validate=false
            - --force=true