# See:
# - https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
# - https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/
# - https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-template-v1/#PodTemplateSpec
# - https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#PodSpec
# - https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#Container
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: http
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: http
