apiVersion: batch/v1
kind: Job
metadata:
  name: fastapi-debug
  namespace: template-fastapi-app
spec:
  template:
    spec:
      containers:
      - name: debug
        image: template-fastapi-app:e9400af-dirty
        command: ["ls", "-la", "/app"]
      restartPolicy: Never
  backoffLimit: 0 