apiVersion: batch/v1
kind: Job
metadata:
  name: fastapi-debug-ls
  namespace: template-fastapi-app
spec:
  template:
    spec:
      containers:
      - name: debug
        image: template-fastapi-app:e9400af-dirty
        command: ["find", "/app", "-name", "token.py"]
      restartPolicy: Never
  backoffLimit: 0 