{{- $env := .Values.environment -}}
{{- range .Values.repositories }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-repo-{{ . }}
  namespace: argocd
  # namespace: argocd-{{$env}}
spec:
  data: 
  - remoteRef:
      key: {{ upper . | replace "-" "_" }}_SSH_PRIVATE_KEY
      version: '1'
    secretKey: sshPrivateKey
  - remoteRef:
      key: {{ upper . | replace "-" "_" }}_REPO_URL
      version: '1'
    secretKey: url
  refreshInterval: {{ $.Values.secretsRefreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ $.Values.clusterSecretStore }}
  target:
    creationPolicy: Owner
    name: argocd-repo-{{ . }}
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
---
{{- end }}
