name: CI

# NOTE: Pushing to a feature branch already builds & test
# on: [push, pull_request]
on: [push]

jobs:
  build:
    # virtual environments: https://github.com/actions/virtual-environments
    runs-on: ubuntu-20.04

    steps:
      # Caches and restores the bazelisk download directory, the bazel build directory.
      - name: Cache bazel
        uses: actions/cache@v3.3.1
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-cache

      # Checks-out your repository under $GITHUB_WORKSPACE, which is the CWD for
      # the rest of the steps
      - name: Checkout code
        uses: actions/checkout@v3

      # See: https://www.buildbuddy.io/docs/rbe-github-actions
      # Use remote build (BuildBuddy)
      - name: Build the code
        run: |
          bazel build \
          --config=ci \
          --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_ORG_API_KEY }} \
          //...

      # See: https://www.buildbuddy.io/docs/rbe-github-actions
      # Use remote build (BuildBuddy)
      - name: Run the test
        run: |
          bazel test \
          --config=ci \
          --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_ORG_API_KEY }} \
          //...

# name: CI

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   ci:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: bazelbuild/setup-bazelisk@v1
#       - run: bazel build //...
#       - run: bazel test //...
