apiVersion: v1
kind: Service
metadata:
  name: calculator-flask-app
  labels:
    app: calculator-flask-app
spec:
  selector:
    app: calculator-flask-app
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  type: ClusterIP